### ISSUE TITLE
[joss-reviews#2974] Python and dependencies version compatibility are missing

### ISSUE THREAD

**Issue by chkoar** [moead-framework/framework#10]
Related: https://github.com/openjournals/joss-reviews/issues/2974

Docs should state the minimum (and the expected maximum) required versions so the package would be able to work.

**Comment by geoffreyp** [comment]
Documentation updated, Readme updated on dev branch

**Comment by chkoar** [comment]
As I can see the package requires `numpy`. Although, I cannot see a minimum required version for `numpy`. Does this mean that it can work with any version of `numpy`?

**Comment by chkoar** [comment]
Classifiers for the supported python versions could be added in the `setup.py`

**Comment by geoffreyp** [comment]
Documentation updated: https://moead-framework.github.io/framework/html/install.html
setup.py: https://github.com/moead-framework/framework/blob/master/setup.py
requirements.txt: https://github.com/moead-framework/framework/blob/master/requirements.txt

**Comment by chkoar** [comment]
Can be closed after #39
