### ISSUE TITLE
[joss-reviews#2974] Add community guidelines

### ISSUE THREAD

**Issue by chkoar** [moead-framework/framework#13]
Related: openjournals/joss-reviews#2974

See [here](https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines).

**Comment by geoffreyp** [comment]
The documentation is updated: 
- https://moead-framework.github.io/documentation/html/index.html
- https://moead-framework.github.io/documentation/html/contributing.html

Two new files: 
- https://github.com/moead-framework/framework/blob/master/CONTRIBUTING.md
- https://github.com/moead-framework/framework/blob/master/CODE_OF_CONDUCT.md

**Comment by sjvrijn** [comment]
Did you copy this from a Docker-related project? There are mentions of 'layers' (line 10) and 'ports' (line 12) which seems irrelevant for this project.

**Comment by geoffreyp** [comment]
It is the file proposed by GitHub, I fixed it

**Comment by sjvrijn** [comment]
The `CONTRIBUTING.md` only really covers pull requests and is not referenced anywhere.

My proposal would be:
 - Add a short section to the README, also referring to the `CONTRIBUTING.md` and code of conduct, stating explicitly what someone can do who 
   - has a question
   - wants to open an issue
   - wants to contribute by submitting a PR

**Comment by geoffreyp** [comment]
I add more information in contributing.md and a section in readme : PR https://github.com/moead-framework/framework/pull/52
