### ISSUE TITLE
[joss-reviews#2974] Consider adding a user guide

### ISSUE THREAD

**Issue by chkoar** [moead-framework/framework#14]
Related: openjournals/joss-reviews#2974

Currently the documentation seems like a single page. Please consider adding a user guide. See [here](https://deap.readthedocs.io/en/master/) for instance.

**Comment by geoffreyp** [comment]
I changed the architecture of the documentation

**Comment by chkoar** [comment]
There is no need for the generated documentation to be included in the repository.

**Comment by sjvrijn** [comment]
@geoffreyp Have you considered hosting the documentation on https://readthedocs.org/ instead of as GitHub pages?
That way there is no need to rebuild it manually after every update, and you don't have to keep the generated html/css in your repository.

**Comment by geoffreyp** [comment]
Hello, I tried readthedocs but after some errors about dependencies, I have just created a GitHub action to rebuild automatically the documentation https://github.com/moead-framework/framework/actions/workflows/docs.yml
Thank you!
