### ISSUE TITLE
[joss-reviews#2974] Improve API docs

### ISSUE THREAD

**Issue by chkoar** [moead-framework/framework#15]
Related: openjournals/joss-reviews#2974

All functions/methods should be documented including example inputs and outputs and their expected types. [This](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html) may help you.

**Comment by geoffreyp** [comment]
Thank you for the tip! 
I move the documentation in this repository and I use autodoc with auto-summary. 
The documentation is for the moment based on the dev branch at this url https://moead-framework.github.io/framework/

**Comment by chkoar** [comment]
The documentation needs a great improvement. For instance:

![image](https://user-images.githubusercontent.com/11897937/107608164-d2ca1600-6c43-11eb-9bf4-22a6e41a51da.png)

**Comment by geoffreyp** [comment]
The API documentation has been improved in the commit 0e45c0eb19e7cde58e747b0723228430d13170fc. All parameters and methods are now explained (type + short description)

**Comment by sjvrijn** [comment]
API documentation is missing for the [solution](https://github.com/moead-framework/framework/tree/master/moead_framework/solution) and [tool](https://github.com/moead-framework/framework/tree/master/moead_framework/tool) folders

**Comment by geoffreyp** [comment]
The documentation for tools is added in the PR https://github.com/moead-framework/framework/pull/55
The documentation for solution is available in the section Main Component: https://moead-framework.github.io/framework/html/main_components.html#solution

**Comment by chkoar** [comment]
Some links do not work. Check `Problem` and `AggregationFunction` [here](https://moead-framework.github.io/framework/html/moead_framework/moead_framework.algorithm.combinatorial.moead.Moead.html#moead_framework.algorithm.combinatorial.moead.Moead) for instance.

**Comment by chkoar** [comment]
1) There are classes, methods or functions that seem public and they do not contain a docstring. I list some below. 
Please consider adding a descriptive docstring or make them "private" in case that is not intended for public use. 

- [ ] `AggregationFunction`
- [ ] `Aggregation.run`
- [ ]  `MoeadDRA.run`
- [ ] `CrossoverAndMutation.run`
- [ ] `Crossover.run`
- [ ]  `BinaryMutation.run`
- [ ]  `DifferentialEvolutionCrossover.run`
- [ ]  `MoeadDeOperators.run`
- [ ] `PolynomialMutation.run`
- [ ] `OffspringGeneratorGeneric.run`
- [ ] `ParentSelector.run`
- [ ] `OneRandomAndCurrentParentSelector.select`
- [ ] `TwoRandomAndCurrentParentSelector.select`
- [ ] `TwoRandomParentSelector.select`
- [ ] `SpsStrategy`
- [ ] `SpsAllSubproblems.get_sub_problems`
- [ ] `MaxEvaluation.test`
- [ ] `KnapsackProblem.f`
- [ ] `KnapsackProblem.generate_random_solution`
- [ ] `Mubqp.generate_random_solution`
- [ ] `Rmnk.f`
- [ ] `Rmnk.generate_random_solution`
- [ ] `Problem`

2. It should be nice to include some execution examples in the class docstrings.
