### ISSUE TITLE
Question regarding the coupling between problems and files

### ISSUE THREAD

**Issue by chkoar** [moead-framework/framework#16]
`Related: openjournals/joss-reviews#2974`

Why the problem classes are coupled with files and not with other data structures?

**Comment by geoffreyp** [comment]
Combinatorial problems implemented (ρMNK-Landscapes, Knapsack and MUBQP) are using instance files. These files are generated with generators (noted in the documentation) by using specific parameters for each instance.  I think it will be complicated to implement these generators in our framework to generate exactly the same instance file with the same seed (to compare the results for the same instance between two algorithms with another framework).

Problem classes are strongly inspired by the example code of the generator's authors (for example: http://svn.code.sf.net/p/mocobench/code/trunk/rmnk/generator/java/)

**Comment by chkoar** [comment]
Since the implemented combinatorial problems are coupled with specific type of problems it should be instantiated using the specific file type and version. 

```python

file_mapping = {
    "rmnk_0_2_100_1_0": ...
}


class Rmnk:
    def __init__(file="rmnk_0_2_100_1_0"):
         if isinstance(file, str):
             ....

```

That way your avoiding the clutter and give the ability to the user to specify the verion of the problem or to pass the file itself is he/she wants to.

**Comment by geoffreyp** [comment]
Sorry but I am not sure to understand, you propose to replace the str attribute `instance_file` (for example "/home/mydir/instances/rmnk_0_2_100_1_0.txt") by the attribute `file` which can be a str (as before with `instance_file`) or directly a file `file=open(instance_file, 'r')`? 

I don't understand the dict `file_mapping` but for example for the Rmnk problem, instance files can be named "instance1.txt" or "rmnk1.txt" because parameters are read in the content of the file and not in the file name, so we can't check the filename.

**Comment by sjvrijn** [comment]
Maybe something like [Pooch](https://pypi.org/project/pooch/) can be of help? Although that's more aimed at larger files.

**Comment by chkoar** [comment]
My point is that requiring external files (even for known problems) makes the things difficult. Take a look [here](https://github.com/jMetal/jMetalPy/blob/master/jmetal/problem/singleobjective/knapsack.py). My proposal is to use instance files directly as a last resort. 1) provide the data directly (I know cumbersome), 2) Using a factory and 3)instance files.

**Comment by chkoar** [comment]
> makes the things difficult.

Even for the example in the readme a user is instructed to go somewhere and download a file.

**Comment by chkoar** [comment]
Let's keep this issue out of  the review
