### ISSUE TITLE
[joss-reviews#2974] A note on reproducibility

### ISSUE THREAD

**Issue by chkoar** [moead-framework/framework#19]
Related: openjournals/joss-reviews#2974

I cannot see a way of controlling the seed on a class level. I suppose that the intention is to control the seed globally via the built-in or the numpy random modules since you use both of them in the package. Although, this is not documented in the docstrings or/and in the documentation.

Some things to consider:
1. Control the seed on class level by passing a seed number or a random state generator object.  Document it in the docstrings.
2. Control the seed globally using a single entry point. Make a note in the documentation.

**Comment by geoffreyp** [comment]
We currently control the seed globally in our projects based on the framework. I add a note in the documentation:
https://moead-framework.github.io/framework/html/tuto.html#manage-the-reproducibility-of-results

**Comment by sjvrijn** [comment]
I strongly agree with @chkoar 's 2nd point that a single point of entry would be better. E.g. adding a `set_seed` function to your `moead_framework.tool` subpackage:

```python
import random
import numpy as np

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
```

This would allow you to easily switch random implementations later without bothering the user, for example if you switch everything to numpy using the new recommended [`np.random.Generator` interface](https://numpy.org/doc/stable/reference/random/generator.html).

**Comment by geoffreyp** [comment]
The function is added with the PR https://github.com/moead-framework/framework/pull/29
