### ISSUE TITLE
[joss-reviews#2974] How to obtain pareto-optimal solutions from moead?

### ISSUE THREAD

**Issue by sjvrijn** [moead-framework/framework#23]
Related: openjournals/joss-reviews#2974

As demonstrated by the provided examples, the `moead.run()` method returns the found pareto-set of solution evaluations, i.e. the output of `f(function_id, solution)`.
I can't however find which (input) solutions correspond to the returned outputs.

How should these solutions be accessed?

**Comment by geoffreyp** [comment]
The `moead.run()` returns a list of [Solution](https://moead-framework.github.io/framework/html/moead_framework/moead_framework.solution.one_dimension_solution.OneDimensionSolution.html#moead_framework.solution.one_dimension_solution.OneDimensionSolution) and not only the output of `f(function_id, solution)`.  
So for each [Solution](https://moead-framework.github.io/framework/html/moead_framework/moead_framework.solution.one_dimension_solution.OneDimensionSolution.html#moead_framework.solution.one_dimension_solution.OneDimensionSolution) x in the list, objective values are available in x.F and variables in x.solution.

I edited the documentation to make it more understandable in the PR https://github.com/moead-framework/framework/pull/28

**Comment by sjvrijn** [comment]
Thanks for the clarification, but even after that it took me 3-4 looks to figure out what you meant. I will split those up into distinct other issues.
