### ISSUE TITLE
[joss-reviews#2974] Paper: grammar/spelling

### ISSUE THREAD

**Issue by sjvrijn** [moead-framework/framework#25]
Related: openjournals/joss-reviews#2974

I'll use this issue to gather all spelling/grammar issues I find in the paper. Additional remarks will be added as content-related issues are fixed (e.g. #24)

6: either capitalize all or none of the relevant words '[M]ulti-[O]bjective [E]volutionary [A]lgorithm based on [D]ecomposition'
10: state-of-[**the**]-art
19: These ~software~ [implementations]
20: state-of-[**the**]-art ... abstraction[,] but ...
21: do not enable [detailed testing and analysis of the various algorithm's components' behavior.]
23: allows [the definition of] different
37&38: ~his/her~ [their] (suggestion, not required)

**Comment by geoffreyp** [comment]
The PR: https://github.com/moead-framework/framework/pull/26/files 
The new pdf is generated here : https://github.com/moead-framework/framework/suites/2316652138/artifacts/48675775

**Comment by sjvrijn** [comment]
One further remark about the following sentence:
>With the moead-framework package, we aim at bringing the modularity of the MOEADr
package by using the flexibility of Python in order to allow the user to update the behavior
of MOEA/D components in their research works, and to propose new variants without being
limited by the software.

When using the verb 'bringing' in this situation, it is usually used as 'bringing ... to ...', meaning I would expect to read something like
> We aim at bringing the modularity of `MOEADr` **to ...**

It is also quite long, so please rewrite it.

**Comment by geoffreyp** [comment]
Edited in the PR https://github.com/moead-framework/framework/pull/54
