### ISSUE TITLE
Confusing OneDimensionalSolution.__repr__

### ISSUE THREAD

**Issue by sjvrijn** [moead-framework/framework#31]
Related: openjournals/joss-reviews#2974 and #23

The `__repr__` of OneDimensionalSolution currently only shows the objective values without any indication it is a more complex object.

This does not follow [Python's recommended usage of the `__repr__` method](https://docs.python.org/3/reference/datamodel.html#object.__repr__) and goes against the [Zen of Python](https://www.python.org/dev/peps/pep-0020/)'s line:
> Explicit is better than implicit

I would strongly recommend changing it such that it can be round-tripped using `eval(repr(x))`  for any `x = OneDimensionalSolution(...)`

**Comment by chkoar** [comment]
I agree. I face a similar issue when trying to create [this](https://github.com/moead-framework/framework/pull/29#issuecomment-809296679) MRE.

**Comment by geoffreyp** [comment]
I add more information in the PR https://github.com/moead-framework/framework/pull/49 

Before: [..., ...., ....]
Now: Solution(F(x)=[..., ...., ....] ; x=[..,..,..,..,..,..])
