### ISSUE TITLE
[Documentation] irrelevant __init__ instruction on documentation for e.g. aggregation functions

### ISSUE THREAD

**Issue by sjvrijn** [moead-framework/framework#33]
Related: openjournals/joss-reviews#2974

For example [here](https://moead-framework.github.io/framework/html/moead_framework/moead_framework.aggregation.tchebycheff.Tchebycheff.html) is the instruction
>__init__()
>   Initialize self. See help(type(self)) for accurate signature.

which gives the following unrelated result in a terminal:

```python
>>> from moead_framework.aggregation import Tchebycheff
>>> help(type(Tchebycheff))
Help on class ABCMeta in module abc:

class ABCMeta(builtins.type)
[...]
```

**Comment by sjvrijn** [comment]
Also related to #15

**Comment by geoffreyp** [comment]
I have a problem with this function, I don't need it and I don't know how to remove it from the documentation... I tried a lot of option in autodoc and autosummary without success

**Comment by sjvrijn** [comment]
> I tried a lot of option in autodoc and autosummary without success

Did you also try the [negated form advanced options](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-option-automodule-special-members)?

Meanwhile, I think the 'core issue' is that the aggregation functions don't specify their own `__init__` (since they don't have any state). It might disappear if you define your own at any point in the inheritance tree?

Although it also makes me wonder what the benefits are of creating stateless objects for this instead of simply having e.g. a file `tchebycheff.py` with functions `run()` and `is_better()`. After all, everything in Python is an object anyway, including imported modules, so you would still be able to use it as

```python
from moead_framework.aggregation import tchebycheff
tchebycheff.run(...)
tchebycheff.is_better(...)
```

So just wondering, did you consider this as an option?

**Comment by geoffreyp** [comment]
Thank you for the link to the documentation. I fixed the problem in the PR https://github.com/moead-framework/framework/pull/57. With autosummary, all class files are forced to add the init method even if it is not documented and without testing the flags no-undoc-members. So I edited the template directly with a custom template for aggregation functions.
