### ISSUE TITLE
Add development requirements

### ISSUE THREAD

**Issue by sjvrijn** [moead-framework/framework#34]
Related: openjournals/joss-reviews#2974

Currently the required packages for building the documentation are only manually specified in the github actions docs.yml file.
A simple `requirements-dev.txt` with those packages (and corresponding install instruction) would help potential contributors to work on the project locally.

**Comment by geoffreyp** [comment]
The file `requirements-dev.txt` and the readme is updated in the PR https://github.com/moead-framework/framework/pull/50
