### ISSUE TITLE
Remove docs/html folder from master branch?

### ISSUE THREAD

**Issue by sjvrijn** [moead-framework/framework#40]
Related: openjournals/joss-reviews#2974

With the documentation being built on a separate gh-pages branch, does that mean the docs/html folder in master is no longer needed?
If so, the repository can be cleaned up by removing it.

**Comment by chkoar** [comment]
I agree

**Comment by geoffreyp** [comment]
the documentation is cleaned in the PR https://github.com/moead-framework/framework/pull/48
