### ISSUE TITLE
[joss-reviews#2974] Ztd1 unfriendly error message

### ISSUE THREAD

**Issue by chkoar** [moead-framework/framework#42]
Related: openjournals/joss-reviews#2974

Ztd1 raises `ZeroDivisionError`. It should reaise a more user friendly message with the correct type of the exception.

```python
from moead_framework.problem.numerical import Zdt1
problem = Zdt1(1)
problem.generate_random_solution()
```

**Comment by geoffreyp** [comment]
It is fixed in the PR https://github.com/moead-framework/framework/pull/51
