### ISSUE TITLE
[joss-reviews#2974] Empty initializer

### ISSUE THREAD

**Issue by chkoar** [moead-framework/framework#43]
Related: openjournals/joss-reviews#2974

Is there a need for [this](https://github.com/moead-framework/framework/blob/892a704f9ce43945d3b2c6343bedee37638fc31e/moead_framework/aggregation/functions.py#L6) empty initializer?

**Comment by geoffreyp** [comment]
I removed it in the PR https://github.com/moead-framework/framework/pull/47
