### ISSUE TITLE
[joss-reviews#2974] Naming confusion

### ISSUE THREAD

**Issue by chkoar** [moead-framework/framework#44]
Related: openjournals/joss-reviews#2974

Something feels strange here. There is a package that is called solution that contains a module which is called solution that contains a class which is called solution that requires a parameter that is called solution.

<img width="669" alt="εικόνα" src="https://user-images.githubusercontent.com/11897937/112845087-24701800-90ad-11eb-97b2-f8775e7d701b.png">

**Comment by geoffreyp** [comment]
I aggree with you, there are several possibilities but I don't know which one would be the best?
- rename the `solution.py` to `abstract_solution.py` and the class `Solution` to `AbstractSolution` ?
- delete the `solution.py`file, is it necessary to have an abstract class here ?

And for the attribute (and parameter) `solution`, I've been wanting to rename it for some time to `decision_vector` or `x`?

**Comment by chkoar** [comment]
In Python we don't have to put each class in a separate package/module. Classes can co-exist in a single module/file. A `base.py` I think that is a common house for abstract/base classes or mixins. Well, naming things is a hard hobby. A solution is represented using a vector which is compose by values, right?
