### ISSUE TITLE
[joss-reviews#2974] Software paper

### ISSUE THREAD

**Issue by chkoar** [moead-framework/framework#70]
Related: openjournals/joss-reviews#2974

**State of the field: Do the authors describe how this software compares to other commonly-used packages?**

In the submitted paper the authors write that "These software offer many state-of-art algorithms, visualization tools or parallelization abstraction but they do not enable to test and analyze in detail the behavior of components implemented in each algorithm"

I cannot understand this statement. @geoffreyp could you elaborate more on this?

cc @sjvrijn I think that is related to https://github.com/openjournals/joss-reviews/issues/2974#issuecomment-869755184

**Comment by geoffreyp** [comment]
The paper was already updated with @sjvrijn (but not the pdf I think) : 

> The first version of MOEA/D and its most famous variants [@moead_de; @moead_dra] are implemented in recent multi-objective optimization software such as pymoo [@pymoo], pygmo [@pygmo] and jMetal [@jmetal]. These implementations offer many state-of-the-art algorithms, visualization tools or parallelization abstraction, but they do not enable detailed testing and analysis of the various algorithm's components' behavior.

**Comment by chkoar** [comment]
> These implementations offer many state-of-the-art algorithms, visualization tools or parallelization abstraction, but they do not enable **detailed testing** and **analysis of** the various algorithm's **components' behavior.**

Since this is the comparative advantage of MOEA/D I think that you should show it in the paper.

**Comment by geoffreyp** [comment]
I suggest adding a sentence: 

> These implementations offer many state-of-the-art algorithms, visualization tools or parallelization abstraction, but they do not enable detailed testing and analysis of the various algorithm's components' behavior. 
> In these libraries, the algorithms are seen as components that do not have sub-components, which makes their parameterization and analysis more difficult, we cannot easily modify their behavior.

**Comment by chkoar** [comment]
> In these libraries, the algorithms are seen as components that do not have sub-components, which makes their parameterization and analysis more difficult, we cannot easily modify their behavior.

I think that this is probably related to #69. Apart from the new text, can you please provide a concrete example of an idea that cannot be implemented with a commonly-used package but can easily be implemented with MOEA/D?

**Comment by geoffreyp** [comment]
With pygmo and Jmetal for example, users are very free to implement new algorithms because they are not restricted by subcomponents, but this also makes it more difficult to implement new algorithms based on MOEA/D. With these frameworks, it is necessary to reimplement a complete algorithm (with code duplication) to implement variants of MOEA/D whereas with our framework, it is only sufficient to implement the component or the function that we want to modify or study. Each of the examples proposed in the documentation cannot therefore be implemented more easily than with our framework.

**Comment by chkoar** [comment]
> With pygmo and Jmetal for example, users are very free to implement new algorithms because they are not restricted by subcomponents, but this also makes it more difficult to implement new algorithms based on MOEA/D. With these frameworks, it is necessary to reimplement a complete algorithm (with code duplication) to implement variants of MOEA/D whereas with our framework, it is only sufficient to implement the component or the function that we want to modify or study. Each of the examples proposed in the documentation cannot therefore be implemented more easily than with our framework.

Here you are trying to explain the modularity that the package offers. I understand.

Although, in the paper pymoo, pygmo and jMetal are mentioned followed by the sentence "..._but they do not enable to test and analyze in detail the behavior of components implemented in each algorithm_"

Either you have to show somehow the aforementioned phrase or you should rephrase.

**Comment by geoffreyp** [comment]
The paper is updated in https://github.com/moead-framework/framework/pull/76 

> These implementations offer many state-of-the-art algorithms, visualization tools or parallelization abstraction, but they are not modular enough to test easily all MOEA/D components.

**Comment by chkoar** [comment]
>  but they are not modular enough to test easily all MOEA/D components.

Should we show somehow this claim?

**Comment by geoffreyp** [comment]
I don't know, I don't see how to demonstrate otherwise that if the other libraries are not modular then we can't test specific components easily without completely reimplementing the algorithm ?

**Comment by chkoar** [comment]
> I don't know, I don't see how to demonstrate otherwise that if the other libraries are not modular then we can't test specific components easily without completely reimplementing the algorithm ?

Could you make a comparison table of moead-framwork with SOTA libraries. Like this you can show a direct comparison without implementing a complete example.

**Comment by geoffreyp** [comment]
Thanks for the advice, the paper is updated on the PR #76

**Comment by chkoar** [comment]
Great
