### ISSUE TITLE
[joss-reviews#2974] Documentation

### ISSUE THREAD

**Issue by chkoar** [moead-framework/framework#71]
Related: openjournals/joss-reviews#2974

**(1) Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).**

There is [an example](https://moead-framework.github.io/framework/html/examples.html) script. Although, I would expect to see several examples that will demonstrate the major components of the software. 

~~**(2) Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?**~~

~~I think that a user guide is missing. User tutorials have been added but I think that they need polishing.~~

**(3) Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?**

The code coverage is great 95%. Although, as I can see the tests cover only the happy path. For instance if you pass not expected types the user should guess what is happening.

~~**(4) Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support**~~

~~I cannot see (2) and (3)~~

**Comment by geoffreyp** [comment]
> There is [an example](https://moead-framework.github.io/framework/html/examples.html) script. Although, I would expect to see several examples that will demonstrate the major components of the software.

I made the choice to propose only one complete example with the initialization of a problem and an algorithm, the execution of an algorithm, the saving of the results and the extraction of information. Would you prefer that I decompose it into several examples?

> I think that a user guide is missing. User tutorials have been added but I think that they need polishing.

What kind of information would you like to see in a user guide? 


> The code coverage is great 95%. Although, as I can see the tests cover only the happy path. For instance if you pass not expected types the user should guess what is happening.

I don't understand the request. Do you have an example of a test to add? The information about the expected types are in the documentation for each function.

> **Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support**
> 
> I cannot see (2) and (3)

This information is available in the Readme and in the documentation : 

<img width="799" alt="image" src="https://user-images.githubusercontent.com/9945579/125062374-9bef1380-e0ae-11eb-95b6-0a03da13fa7a.png">

**Comment by chkoar** [comment]
**(1)**
I would like to see specific examples that will show the value of the library. Take an example what we are discussing [here](https://github.com/moead-framework/framework/issues/69#issuecomment-882625819). Create a new variant without being limited by the software and show the performance benefit using the new variant. [Sphinx-Gallery](https://sphinx-gallery.github.io/stable/index.html) might help you to show this.

**(2)**
DEAP makes a walk though in their [basic tutorials](https://deap.readthedocs.io/en/master/tutorials/basic/part1.html) showing how every components can be used in order to solve a real optimization problem.


**(3)**
> I don't understand the request. Do you have an example of a test to add? The information about the expected types are in the documentation for each function.

I was trying to say that the happy path is now always enough. 
```python
In [8]: KnapsackProblem(1,10)

OSError: [Errno 6] Device not configured
```

**(4)**
Sorry I missed this. I was looking on the documentation pages [here](https://moead-framework.github.io/framework/html/contributing.html). Could you please also add the information there? There are no links.

**Comment by geoffreyp** [comment]
New examples are available in the PR : https://github.com/moead-framework/framework/pull/72
The user guide is available in the PR https://github.com/moead-framework/framework/pull/73
The page contributing was updated with information from README.md

**Comment by chkoar** [comment]
> New examples are available in the PR : #72
The user guide is available in the PR #73
The page contributing was updated with information from README.md

Can you please render the updated documentation?

**Comment by geoffreyp** [comment]
To render the documentation, I have to merge the PR in Master.
The documentation can be generated locally if you want check changes. The documentation is generated with sphinx 2.4.4 (see the section 'Requirements for developers' of the README).

You can generate the documentation with the following commands :

    cd docs/

    make html

**Comment by chkoar** [comment]
This issue raise concerns regarding 4 checks. Can you please point me where (PR/branch) each concern is addressed? Thanks.

**Comment by geoffreyp** [comment]
New examples are available in the PR : #72 (merged by error when the issue https://github.com/moead-framework/framework/issues/69 was closed)
The user guide is available in the PR #73
The contributing page is updated in the PR #73

For the last check : 

> The code coverage is great 95%. Although, as I can see the tests cover only the happy path. For instance if you pass not expected types the user should guess what is happening.

do you have a recommendation for this? Do I have to test each type of parameter, even if types are specified in the documentation?

**Comment by chkoar** [comment]
> do you have a recommendation for this?

[hypothesis](https://hypothesis.readthedocs.io) (and [mutmut](https://mutmut.readthedocs.io)) might help you in this regard.

> Do I have to test each type of parameter, even if types are specified in the documentation?

Since you are in the process of publishing the library I think that you should validate each parameter (for value or/and type) and raise a human friendly error message.

**Comment by geoffreyp** [comment]
Each parameter of Problem and Moead are tested in the PR https://github.com/moead-framework/framework/pull/77

**Comment by chkoar** [comment]
```
def test_that_zdt1_size():
    from moead_framework.problem.numerical import Zdt1
    Zdt1(1)
```

**Comment by geoffreyp** [comment]
> The following test fails but the message is misleading

The message is updated in #77

**Comment by chkoar** [comment]
Can you please merge all remaining PRs to a `review` branch?
I have checked everything.  Can you please test for the expected errors and not only for the happy path?

**Comment by chkoar** [comment]
Can you please merge all remaining PRs to a `review` branch?
I have checked almost everything.  
Can you please test for the expected errors and not only for the happy path?

**Comment by geoffreyp** [comment]
I added unit tests for the unhappy/sad path in the PR https://github.com/moead-framework/framework/pull/77.
All PRs (the last 4) are merged in the branch [review](https://github.com/moead-framework/framework/tree/review).

**Comment by chkoar** [comment]
Great thank you.

The following seem to raise exceptions but they are not tested. Could you please add them?
```
GeneticOperator.number_of_solution_is_correct
DeltaSelector.__init__
SpsDra.get_sub_problems
SpsRandomAndBoundaries.get_sub_problems
```


In general I think that all components that are listed for public consumption should be properly tested for behavior and exceptions. So, the user should be informed accordingly.  In general do not trust users input. Some examples, for instance. 
```python
# test/test_genetic_operator.py

# I am allowed to pass a string in the mutation but when I run the mutation the message is not informative
# Result: TypeError: unsupported operand type(s) for -: 'str' and 'int'
def test_binary_mutattion_example1():
    array_solution = ["a",0]
    new_solution = BinaryMutation(solutions=[array_solution]).run()

# Should this be allowed?
# Result: [0.10000000000000009, 0.3999999999999999]
def test_binary_mutattion_example2():
    array_solution = [1.1, 1.4]
    new_solution = BinaryMutation(solutions=[array_solution]).run()

# Tried to pass a single array
# Result: TypeError: object of type 'int' has no len()
def test_binary_mutattion_example3():
    array_solution = [0, 1]
    new_solution = BinaryMutation(solutions=array_solution).run()

# Tried to pass an integer
# Result: TypeError: 'int' object is not subscriptable
def test_binary_mutattion_example4():
    array_solution = [0, 1]
    new_solution = BinaryMutation(solutions=array_solution).run()

# Tried to pass empty arrays
# Result: ZeroDivisionError: division by zero
def test_binary_mutattion_example5():
    array_solution = [0, 1]
    new_solution = BinaryMutation(solutions=[[]]).run()

# Tried to ask more crossover points than the length
# Result: Infinite loop
def test_crossover_example1():
    array_solution1 = [1, 2, 3, 4, 5]
    array_solution2 = [6, 7, 8, 9, 10]
    new_solution_one_point = Crossover(solutions=[array_solution1, array_solution2],crossover_points=10).run().tolist()

# Tried to ask a zero crossover points than the length
# Result: IndexError: list index out of range
def test_crossover_example1():
    array_solution1 = [1, 2, 3, 4, 5]
    array_solution2 = [6, 7, 8, 9, 10]
    new_solution_one_point = Crossover(solutions=[array_solution1, array_solution2],crossover_points=0).run().tolist()

```

**Comment by geoffreyp** [comment]
All unit tests are added on the branch review

**Comment by chkoar** [comment]
Hey @geoffreyp , I made some comments in individual commits in the review brunch. Did you get notified?

**Comment by geoffreyp** [comment]
I have received the notifications, I will check
