### ISSUE TITLE
Imports are very long

### ISSUE THREAD

**Issue by sjvrijn** [moead-framework/framework#9]
The example in the README starts with the following long imports:

```python
from moead_framework.aggregation.tchebycheff import Tchebycheff
from moead_framework.algorithm.combinatorial.moead import Moead
from moead_framework.problem.combinatorial.rmnk import Rmnk
from moead_framework.tool.result import save_population
```

I would at least simplify them to remove the 'double' specifications, using your subfolders' `__init__.py` files
For example simplifying
```python
from moead_framework.aggregation.tchebycheff import Tchebycheff
```
to
```python
from moead_framework.aggregation import Tchebycheff
```
 by adding the line
```python
from tchebycheff import Tchebycheff
```
to your [`aggregation/__init__.py`](https://github.com/moead-framework/framework/blob/master/moead_framework/aggregation/__init__.py).

You could also consider further simplifying `problem.combinatorial` to just `problem`, etc... But that is more up to personal preference.

**Comment by geoffreyp** [comment]
Thank you for the tip ! 
It is updated in the commit 4fa33886bc5d4dee8a8f45a461f99d37f845992c. I will merge it in Master branch for a new release when the documentation will be updated
